name: Flutter CI

# This workflow is triggered on pull_request to [ deployment ] to the repository.

on:
  pull_request:
    branches:
      - deploy
# on: push    # Default will running for every branch.

jobs:
  build:
    name: Build the release-apk
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '2.10.3' # you can also specify exact version of flutter

      # Get flutter dependencies.
      # - run: mkdir build
      # - run: touch test.txt

      - run: flutter pub get

      # # Check for any formatting issues in the code.
      # # - run: flutter format --set-exit-if-changed .

      # # Statically analyze the Dart code for any errors.
      # # - run: flutter analyze .

      # # Run widget tests for our flutter project.
      # # - run: flutter test

      # Build apk.
      - run: flutter build apk --release

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # send_email
      - name: Sending mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: test.hari.v1@gmail.com
          # Optional (recommended) mail server password:
          password: njozkzkuudptjqcl
          # Required mail subject:
          subject: ${{github.repository}} build result
          # Required recipients' addresses:
          to: harikrishnan.r@harvestinfosoft.com
          # Required sender full name (address can be skipped):
          from: Harikrishnan # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!

          attachments: build/app/outputs/apk/release/app-release.apk
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low
